name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: ğŸ”¨ Build ğŸ§ª Test ğŸ§¹ Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸŸ© Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          
          
          
          
          

      - name: ğŸŸ¢ Install node modules
        run: npm ci

      - name: ğŸ”¨ Build
        run: npm run build

      # - name: ğŸ§ª Test
      #   run: npm run test

      - name: ğŸ§¹ Lint Demo
        run: npm run lint

      - name: ğŸ’¾ Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib/

  publish_npm:
    name: ğŸ”´ NPM publish
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ğŸŸ© Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: â¬‡ï¸ Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: lib

      - name: ğŸ”´ NPM publish
        continue-on-error: true
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish

  publish_github:
    name: ğŸ˜º GitHub publish
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ğŸŸ© Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: â¬‡ï¸ Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: lib

      - name: Update package.json name ğŸ“
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: name
          value: "@${{ github.repository_owner }}/${{ github.event.repository.name }}"

      - name: ğŸ˜º GitHub publish
        continue-on-error: true
        env:
          OWNER: ${{ github.repository_owner }}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "@${OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
          npm publish
